### ISSUE TITLE
Offset in %

### ISSUE THREAD

**Issue by smilefootage** [edull24/ScrollWatch#15]
Hey there,

any chance to set something up to check if the scroll element has reached the top of the window instead of checking that it came into the viewport?

best,
marcel

**Comment by edull24** [comment]
Hi Marcel,

You can accomplish this a number of ways, depending on your exact needs and circumstances.

In the simplest scenario of wanting to know when an element has been scrolled to the top of the window due to scrolling the page down, you can simply use a dummy element placed directly above the element in question. When that element has scrolled out of view, you know your element is at the top.

You can view an example here: https://codepen.io/edull24/pen/vYKBXxY

If you have a more complicated use case, I suggest using a combination of dummy elements, onElementInView/onElementOutOfView callbacks, and/or watch offset options.
